default:
  image: python:3.10
  before_script:
    - pip install -U pip

stages:
  - test
  - build

.base_test:
  stage: test
  script:
    - pip install -U tox
    - tox -e py

test:
  image: python:${PYTHONVERSION}
  parallel:
    matrix:
      - PYTHONVERSION:
          - "3.10"
  extends:
    - .base_test

test:lint:
  stage: test
  script:
    - pip install -U tox
    - tox -e isort
    - tox -e pylint

build:pypi:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" &&
        $CI_PROJECT_NAME == "fastapi-authlib"  &&
        $CI_PROJECT_NAMESPACE == "zncdata/develop"  &&
        $REGISTRY_USER  &&
        $REGISTRY_PASSWORD
      when: on_success

  before_script:
    - export PYPI_REPO_NAME=pypi
    - export PYPI_REPO_URL=https://pypi.org/
    - pip install poetry
    - poetry config repositories.${PYPI_REPO_NAME} $PYPI_REPO_URL
    - poetry config pypi-token.pypi $PYPI_TOKEN
  script:
    - poetry publish -r $PYPI_REPO_NAME --build
